export const GRAMMAR = {
	PROGRAM: [
		["PROGRAM_END"],
		["TERMINATOR", "PROGRAM"],
		["STATEMENT", "PROGRAM_NEXT"],
	],
	PROGRAM_NEXT: [
		["TERMINATOR", "PROGRAM"],
		["PROGRAM_END"],
	],
	STATEMENT: [
		["EXPRESSION", "COMMENT"],
		["COMMENT"],
		["EXPRESSION"],
	],
	EXPRESSION: [
		["OPEN_PARENTHESIS", "EXPRESSION", "CLOSE_PARENTHESIS", "BARE_EXPRESSION"],
		["FUNCTION", "BARE_EXPRESSION"],
		["TERM", "BARE_EXPRESSION"],
	],
	BARE_EXPRESSION: [
		["OPERATOR", "EXPRESSION"],
		[],
	],
	OP_EXPRESSION: [["EXPRESSION", "OPERATOR", "EXPRESSION"]],
	OPERATOR: [
		["PLUS"],
		["MINUS"],
		["DIVIDE"],
		["POWER"],
		["MULTIPLY"],
	],
	FUNCTION: [
		["IDENTIFIER", "OPEN_PARENTHESIS", "CLOSE_PARENTHESIS"],
		["IDENTIFIER", "OPEN_PARENTHESIS", "ARG_LIST", "CLOSE_PARENTHESIS"],
	],
	ARG_LIST: [
		["EXPRESSION", "COMMA", "ARG_LIST"],
		["EXPRESSION"],
	],
	TERM: [
		["NUMBER"],
		["MINUS", "NUMBER"],
		["IDENTIFIER"],
		["STRING"],
	],
	TERMINATOR: [["STMT_END"], ["NEWLINE"]],
};

export default GRAMMAR;
