export const GRAMMAR = {
	PROGRAM: [
		["PROGRAM_END"],
		["TERMINATOR", "PROGRAM"],
		["STATEMENT", "PROGRAM_NEXT"],
	],
	PROGRAM_NEXT: [
		["TERMINATOR", "PROGRAM"],
		["PROGRAM_END"],
	],
	STATEMENT: [
		["EXPRESSION_1", "COMMENT"],
		["COMMENT"],
		["EXPRESSION_1"],
	],

	// Right associativity is fine here, since we correct it during execution.
	EXPRESSION_1: [
		["EXPRESSION_2", "OPERATOR_1", "EXPRESSION_1"],
		["EXPRESSION_2"],
	],
	EXPRESSION_2: [
		["EXPRESSION_3", "OPERATOR_2", "EXPRESSION_2"],
		["EXPRESSION_3"],
	],
	EXPRESSION_3: [
		["FACTOR", "OPERATOR_3", "EXPRESSION_3"],
		["FACTOR"],
	],
	OPERATOR_1: [
		["PLUS"],
		["MINUS"],
	],
	OPERATOR_2: [
		["DIVIDE"],
		["MULTIPLY"],
	],
	OPERATOR_3: [
		["POWER"],
	],
	FUNCTION: [
		["IDENTIFIER", "OPEN_PARENTHESIS", "CLOSE_PARENTHESIS"],
		["IDENTIFIER", "OPEN_PARENTHESIS", "ARG_LIST", "CLOSE_PARENTHESIS"],
	],
	ARG_LIST: [
		["EXPRESSION_1", "COMMA", "ARG_LIST"],
		["EXPRESSION_1"],
	],
	FACTOR: [
		["NUMBER"],
		["MINUS", "NUMBER"],
		["FUNCTION"],
		["IDENTIFIER"],
		["STRING"],
		["OPEN_PARENTHESIS", "EXPRESSION_1", "CLOSE_PARENTHESIS"]
	],
	TERMINATOR: [["STMT_END"], ["NEWLINE"]],
};

export default GRAMMAR;
